### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by TheNomad11** [williamjacksn/pblive#34]
I tried to install it on a Ubuntu 20 VPS. On running the last command `python -m pblive` I got this error message

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/USER/pblive/pblive/__main__.py", line 46, in <module>
    for f in os.listdir('data'):
FileNotFoundError: [Errno 2] No such file or directory: 'data'
```
When trying the docker example I got these errors:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/pblive/pblive/__main__.py", line 49, in <module>
    with open(os.path.join('data', f)) as fh:
IsADirectoryError: [Errno 21] Is a directory: 'data/example.yaml'
```
I am no sysadmin, just learning...

**Comment by williamjacksn** [comment]
Do you have a data folder at `/home/USER/pblive/data` with at least one `.yml` file describing your questions? The README has the details about what you need.

**Comment by TheNomad11** [comment]
Thanks, stupid me, that was the reason! Works now
